// Package dns generates DNS Response Policy Zone (RPZ) files from policy rules.
//
// RPZ is a DNS-level enforcement mechanism: denied domains resolve to NXDOMAIN
// (via CNAME .) instead of their real IPs. This prevents agents from even
// establishing connections to blocked destinations.
//
// Reference: RFC 7719, ISC RPZ specification.
package dns

import (
	"fmt"
	"os"
	"strings"
	"time"

	"github.com/bufordtjustice2918/crispy-garbanzo/internal/policy"
)

// RPZConfig controls zone generation parameters.
type RPZConfig struct {
	ZoneName   string // e.g. "rpz.clawgress.local"
	SOAContact string // e.g. "admin.clawgress.local"
	TTL        int    // default 60
	Serial     uint32 // 0 = auto-generate from timestamp
}

// RPZResult is returned after generating a zone file.
type RPZResult struct {
	ZonePath    string `json:"zone_path"`
	DeniedCount int    `json:"denied_count"`
	Serial      uint32 `json:"serial"`
	GeneratedAt string `json:"generated_at"`
}

// GenerateRPZ creates an RPZ zone file from deny rules in the policy engine.
// Only "deny" rules produce RPZ entries (CNAME .). Allow rules are not
// represented in RPZ — allowed domains resolve normally.
func GenerateRPZ(rules []policy.Rule, cfg RPZConfig) string {
	if cfg.ZoneName == "" {
		cfg.ZoneName = "rpz.clawgress.local"
	}
	if cfg.SOAContact == "" {
		cfg.SOAContact = "admin.clawgress.local"
	}
	if cfg.TTL == 0 {
		cfg.TTL = 60
	}
	if cfg.Serial == 0 {
		cfg.Serial = uint32(time.Now().Unix())
	}

	var sb strings.Builder

	// SOA and NS records.
	sb.WriteString(fmt.Sprintf("; RPZ zone generated by Clawgress at %s\n", time.Now().UTC().Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("$TTL %d\n", cfg.TTL))
	sb.WriteString(fmt.Sprintf("@ IN SOA %s. %s. (\n", cfg.ZoneName, cfg.SOAContact))
	sb.WriteString(fmt.Sprintf("    %d ; serial\n", cfg.Serial))
	sb.WriteString("    3600   ; refresh\n")
	sb.WriteString("    600    ; retry\n")
	sb.WriteString("    86400  ; expire\n")
	sb.WriteString(fmt.Sprintf("    %d     ; minimum TTL\n", cfg.TTL))
	sb.WriteString(")\n")
	sb.WriteString(fmt.Sprintf("@ IN NS %s.\n\n", cfg.ZoneName))

	// Deny rules → CNAME . (NXDOMAIN).
	seen := make(map[string]bool)
	for _, r := range rules {
		if r.Action != "deny" {
			continue
		}
		for _, d := range r.Domains {
			if d == "*" {
				continue // can't block everything via RPZ
			}
			// Normalize: strip wildcard prefix for RPZ format.
			rpzName := d
			if strings.HasPrefix(d, "*.") {
				// *.evil.com → block evil.com AND *.evil.com
				base := d[2:]
				if !seen[base] {
					sb.WriteString(fmt.Sprintf("%-40s CNAME .\n", base))
					seen[base] = true
				}
				rpzName = "*." + base
			}
			if !seen[rpzName] {
				sb.WriteString(fmt.Sprintf("%-40s CNAME .\n", rpzName))
				seen[rpzName] = true
			}
		}
	}

	return sb.String()
}

// WriteRPZFile generates and writes the RPZ zone file to disk atomically.
func WriteRPZFile(path string, rules []policy.Rule, cfg RPZConfig) (*RPZResult, error) {
	content := GenerateRPZ(rules, cfg)

	// Count denied entries.
	denied := 0
	for _, line := range strings.Split(content, "\n") {
		if strings.Contains(line, "CNAME .") && !strings.HasPrefix(line, ";") {
			denied++
		}
	}

	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0o644); err != nil {
		return nil, fmt.Errorf("write RPZ zone: %w", err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return nil, fmt.Errorf("rename RPZ zone: %w", err)
	}

	if cfg.Serial == 0 {
		cfg.Serial = uint32(time.Now().Unix())
	}

	return &RPZResult{
		ZonePath:    path,
		DeniedCount: denied,
		Serial:      cfg.Serial,
		GeneratedAt: time.Now().UTC().Format(time.RFC3339),
	}, nil
}

// GenerateNamedConf renders a bind9 named.conf.local snippet that references the RPZ zone.
func GenerateNamedConf(zoneName, zoneFilePath string) string {
	if zoneName == "" {
		zoneName = "rpz.clawgress.local"
	}
	if zoneFilePath == "" {
		zoneFilePath = "/etc/bind/db.rpz.clawgress"
	}

	return fmt.Sprintf(`// Clawgress RPZ zone — auto-generated, do not edit
zone "%s" {
    type master;
    file "%s";
    allow-query { any; };
};

options {
    response-policy {
        zone "%s";
    };
};
`, zoneName, zoneFilePath, zoneName)
}
